/**
 * SPR-MOD-001-003 — Phase 3 Gate 3.3 · Supabase provider types.
 *
 * Ports and typed models only. Every dependency is injected: no env reads,
 * no globals, no singletons. The provider is STATELESS — it caches no project
 * status and no execution progress; all provisioning state lives in the
 * orchestrator.
 */
import type { Json, MigrationRecord, SecretReference } from "../../types";

/* -------------------------------------------------------------------------- */
/* Credentials                                                                 */
/* -------------------------------------------------------------------------- */

export interface SupabaseCredentials {
  accessToken: string;
  organizationId: string;
}

/**
 * Resolves credentials PER PROVISIONING REQUEST (never globally), so
 * multi-tenant credentials and rotation need no re-wiring.
 */
export interface SecretResolver {
  resolve(reference: SecretReference, ctx: ProviderCallContext): Promise<SupabaseCredentials>;
}

/* -------------------------------------------------------------------------- */
/* Call context and logging                                                    */
/* -------------------------------------------------------------------------- */

export interface ProviderCallContext {
  correlationId: string;
  tenantId?: string | null;
  projectId?: string | null;
  operation: string;
}

export type ProviderLogFields = ProviderCallContext & Record<string, unknown>;

export interface ProviderLogger {
  debug(message: string, fields: ProviderLogFields): void;
  info(message: string, fields: ProviderLogFields): void;
  warn(message: string, fields: ProviderLogFields): void;
  error(message: string, fields: ProviderLogFields): void;
}

/* -------------------------------------------------------------------------- */
/* Clock                                                                       */
/* -------------------------------------------------------------------------- */

export interface ProviderClock {
  /** Epoch milliseconds. */
  nowMs(): number;
  /** ISO-8601 timestamp. */
  nowIso(): string;
  /** Resolves after `ms`; rejects nothing — cancellation is signalled separately. */
  sleep(ms: number, signal?: AbortSignal): Promise<void>;
}

/* -------------------------------------------------------------------------- */
/* HTTP transport                                                              */
/* -------------------------------------------------------------------------- */

export type FetchLike = (
  input: string,
  init?: {
    method?: string;
    headers?: Record<string, string>;
    body?: string;
    signal?: AbortSignal;
  },
) => Promise<HttpResponseLike>;

export interface HttpResponseLike {
  status: number;
  ok: boolean;
  headers: { get(name: string): string | null };
  text(): Promise<string>;
}

/* -------------------------------------------------------------------------- */
/* Management API models                                                       */
/* -------------------------------------------------------------------------- */

export type ProjectStatus =
  | "COMING_UP"
  | "ACTIVE_HEALTHY"
  | "ACTIVE_UNHEALTHY"
  | "INIT_FAILED"
  | "REMOVED"
  | "UNKNOWN";

export interface ProjectInfo {
  id: string;
  /** Project reference used by every subsequent Management API call. */
  reference: string;
  name: string;
  organizationId: string;
  region: string;
  status: ProjectStatus;
  createdAt: string | null;
}

export interface CreateProjectRequest {
  name: string;
  region: string;
  /** Generated by the caller; never logged. */
  databasePassword: string;
}

export interface DatabaseConnection {
  host: string;
  port: number;
  database: string;
  username: string;
  password: string;
  sslMode: "require" | "disable";
}

export interface ProjectApiKeys {
  anonKey: string;
  serviceRoleKey: string;
  projectUrl: string;
}

/* -------------------------------------------------------------------------- */
/* SQL execution                                                               */
/* -------------------------------------------------------------------------- */

export interface SqlQueryInput {
  projectReference: string;
  sql: string;
  /** Diagnostic label only; never interpolated into SQL. */
  label?: string;
  signal?: AbortSignal;
}

export type SqlRow = Record<string, Json | undefined>;

export interface SqlResult {
  rows: SqlRow[];
}

/**
 * Executes SQL statements handed to it and nothing more.
 *
 * BOUNDARY: no sequencing, no ordering, no checksum handling, no business
 * logic. Those belong to the migration and seed runners.
 */
export interface SqlExecutor {
  execute(input: SqlQueryInput): Promise<SqlResult>;
}

/* -------------------------------------------------------------------------- */
/* Migration + seed sources                                                    */
/* -------------------------------------------------------------------------- */

export interface MigrationScript {
  version: string;
  name: string;
  checksum: string;
  sql: string;
}

/** Supplies ordered migration scripts. No filesystem access at runtime. */
export interface MigrationSource {
  list(): Promise<readonly MigrationScript[]>;
}

export interface SeedScript {
  name: string;
  sql: string;
  /**
   * Verification query returning at least one row when the seed is present.
   * Used both for idempotency and for the health check.
   */
  verifySql: string;
}

export interface SeedSource {
  list(): Promise<readonly SeedScript[]>;
}

/* -------------------------------------------------------------------------- */
/* Auth Admin                                                                  */
/* -------------------------------------------------------------------------- */

export interface CreateAdminUserInput {
  projectUrl: string;
  serviceRoleKey: string;
  email: string;
  signal?: AbortSignal;
}

export interface AuthAdminApi {
  createUser(input: CreateAdminUserInput): Promise<{ userId: string }>;
  findUserByEmail(input: CreateAdminUserInput): Promise<{ userId: string } | null>;
}

/* -------------------------------------------------------------------------- */
/* Configuration + dependencies                                                */
/* -------------------------------------------------------------------------- */

export interface ReadinessPolicy {
  maxAttempts: number;
  baseDelayMs: number;
  maxDelayMs: number;
  multiplier: number;
}

export interface SupabaseProviderConfig {
  /** Management API base URL, injected (defaults applied by the factory). */
  apiBaseUrl: string;
  organizationId: string;
  defaultRegion: string;
  readiness: ReadinessPolicy;
  /** Tag stored in the project name so duplicate requests are detectable. */
  projectNamePrefix: string;
}

export interface SupabaseProviderDeps {
  config: SupabaseProviderConfig;
  secrets: SecretResolver;
  fetch: FetchLike;
  clock: ProviderClock;
  logger: ProviderLogger;
  migrations: MigrationSource;
  seeds: SeedSource;
  authAdmin: AuthAdminApi;
  /** Injected so a pg / Neon / RDS-proxy executor can replace the API one. */
  createSqlExecutor?: (credentials: SupabaseCredentials) => SqlExecutor;
  /** Cancels in-flight polling and requests. */
  signal?: AbortSignal;
  /** Deterministic in tests. */
  passwordFactory?: () => string;
}

/* -------------------------------------------------------------------------- */
/* Results                                                                     */
/* -------------------------------------------------------------------------- */

export interface AppliedMigrations {
  applied: MigrationRecord[];
  skipped: MigrationRecord[];
}

export interface SeedResult {
  executed: string[];
  skipped: string[];
}

export interface DestroyResult {
  deleted: boolean;
  verified: boolean;
  orphans: Array<{ kind: string; reference: string; reason: string }>;
}
