/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as R500RouteImport } from './routes/500'
import { Route as R403RouteImport } from './routes/403'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsSplatRouteImport } from './routes/docs.$'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedPlatformIndexRouteImport } from './routes/_authenticated/platform/index'
import { Route as AuthenticatedPlatformDashboardRouteImport } from './routes/_authenticated/platform/dashboard'
import { Route as AuthenticatedPlatformSplatRouteImport } from './routes/_authenticated/platform/$'
import { Route as AuthenticatedPlatformProvisioningRouteRouteImport } from './routes/_authenticated/platform/provisioning/route'
import { Route as AuthenticatedPlatformTenantsIndexRouteImport } from './routes/_authenticated/platform/tenants/index'
import { Route as AuthenticatedPlatformProvisioningIndexRouteImport } from './routes/_authenticated/platform/provisioning/index'
import { Route as AuthenticatedPlatformCompaniesIndexRouteImport } from './routes/_authenticated/platform/companies/index'
import { Route as AuthenticatedPlatformTenantsTenantIdRouteImport } from './routes/_authenticated/platform/tenants/$tenantId'
import { Route as AuthenticatedPlatformProvisioningQueueRouteImport } from './routes/_authenticated/platform/provisioning/queue'
import { Route as AuthenticatedPlatformProvisioningHistoryRouteImport } from './routes/_authenticated/platform/provisioning/history'
import { Route as AuthenticatedPlatformProvisioningHealthRouteImport } from './routes/_authenticated/platform/provisioning/health'
import { Route as AuthenticatedPlatformProvisioningFailedRouteImport } from './routes/_authenticated/platform/provisioning/failed'
import { Route as AuthenticatedPlatformProvisioningJobIdRouteImport } from './routes/_authenticated/platform/provisioning/$jobId'
import { Route as AuthenticatedPlatformCompaniesCompanyIdRouteImport } from './routes/_authenticated/platform/companies/$companyId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const R500Route = R500RouteImport.update({
  id: '/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DocsRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedPlatformIndexRoute =
  AuthenticatedPlatformIndexRouteImport.update({
    id: '/platform/',
    path: '/platform/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlatformDashboardRoute =
  AuthenticatedPlatformDashboardRouteImport.update({
    id: '/platform/dashboard',
    path: '/platform/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlatformSplatRoute =
  AuthenticatedPlatformSplatRouteImport.update({
    id: '/platform/$',
    path: '/platform/$',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlatformProvisioningRouteRoute =
  AuthenticatedPlatformProvisioningRouteRouteImport.update({
    id: '/platform/provisioning',
    path: '/platform/provisioning',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlatformTenantsIndexRoute =
  AuthenticatedPlatformTenantsIndexRouteImport.update({
    id: '/platform/tenants/',
    path: '/platform/tenants/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlatformProvisioningIndexRoute =
  AuthenticatedPlatformProvisioningIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPlatformProvisioningRouteRoute,
  } as any)
const AuthenticatedPlatformCompaniesIndexRoute =
  AuthenticatedPlatformCompaniesIndexRouteImport.update({
    id: '/platform/companies/',
    path: '/platform/companies/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlatformTenantsTenantIdRoute =
  AuthenticatedPlatformTenantsTenantIdRouteImport.update({
    id: '/platform/tenants/$tenantId',
    path: '/platform/tenants/$tenantId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlatformProvisioningQueueRoute =
  AuthenticatedPlatformProvisioningQueueRouteImport.update({
    id: '/queue',
    path: '/queue',
    getParentRoute: () => AuthenticatedPlatformProvisioningRouteRoute,
  } as any)
const AuthenticatedPlatformProvisioningHistoryRoute =
  AuthenticatedPlatformProvisioningHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedPlatformProvisioningRouteRoute,
  } as any)
const AuthenticatedPlatformProvisioningHealthRoute =
  AuthenticatedPlatformProvisioningHealthRouteImport.update({
    id: '/health',
    path: '/health',
    getParentRoute: () => AuthenticatedPlatformProvisioningRouteRoute,
  } as any)
const AuthenticatedPlatformProvisioningFailedRoute =
  AuthenticatedPlatformProvisioningFailedRouteImport.update({
    id: '/failed',
    path: '/failed',
    getParentRoute: () => AuthenticatedPlatformProvisioningRouteRoute,
  } as any)
const AuthenticatedPlatformProvisioningJobIdRoute =
  AuthenticatedPlatformProvisioningJobIdRouteImport.update({
    id: '/$jobId',
    path: '/$jobId',
    getParentRoute: () => AuthenticatedPlatformProvisioningRouteRoute,
  } as any)
const AuthenticatedPlatformCompaniesCompanyIdRoute =
  AuthenticatedPlatformCompaniesCompanyIdRouteImport.update({
    id: '/platform/companies/$companyId',
    path: '/platform/companies/$companyId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/500': typeof R500Route
  '/auth': typeof AuthRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/': typeof DocsIndexRoute
  '/platform/provisioning': typeof AuthenticatedPlatformProvisioningRouteRouteWithChildren
  '/platform/$': typeof AuthenticatedPlatformSplatRoute
  '/platform/dashboard': typeof AuthenticatedPlatformDashboardRoute
  '/platform/': typeof AuthenticatedPlatformIndexRoute
  '/platform/companies/$companyId': typeof AuthenticatedPlatformCompaniesCompanyIdRoute
  '/platform/provisioning/$jobId': typeof AuthenticatedPlatformProvisioningJobIdRoute
  '/platform/provisioning/failed': typeof AuthenticatedPlatformProvisioningFailedRoute
  '/platform/provisioning/health': typeof AuthenticatedPlatformProvisioningHealthRoute
  '/platform/provisioning/history': typeof AuthenticatedPlatformProvisioningHistoryRoute
  '/platform/provisioning/queue': typeof AuthenticatedPlatformProvisioningQueueRoute
  '/platform/tenants/$tenantId': typeof AuthenticatedPlatformTenantsTenantIdRoute
  '/platform/companies/': typeof AuthenticatedPlatformCompaniesIndexRoute
  '/platform/provisioning/': typeof AuthenticatedPlatformProvisioningIndexRoute
  '/platform/tenants/': typeof AuthenticatedPlatformTenantsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/500': typeof R500Route
  '/auth': typeof AuthRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs': typeof DocsIndexRoute
  '/platform/$': typeof AuthenticatedPlatformSplatRoute
  '/platform/dashboard': typeof AuthenticatedPlatformDashboardRoute
  '/platform': typeof AuthenticatedPlatformIndexRoute
  '/platform/companies/$companyId': typeof AuthenticatedPlatformCompaniesCompanyIdRoute
  '/platform/provisioning/$jobId': typeof AuthenticatedPlatformProvisioningJobIdRoute
  '/platform/provisioning/failed': typeof AuthenticatedPlatformProvisioningFailedRoute
  '/platform/provisioning/health': typeof AuthenticatedPlatformProvisioningHealthRoute
  '/platform/provisioning/history': typeof AuthenticatedPlatformProvisioningHistoryRoute
  '/platform/provisioning/queue': typeof AuthenticatedPlatformProvisioningQueueRoute
  '/platform/tenants/$tenantId': typeof AuthenticatedPlatformTenantsTenantIdRoute
  '/platform/companies': typeof AuthenticatedPlatformCompaniesIndexRoute
  '/platform/provisioning': typeof AuthenticatedPlatformProvisioningIndexRoute
  '/platform/tenants': typeof AuthenticatedPlatformTenantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/500': typeof R500Route
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/': typeof DocsIndexRoute
  '/_authenticated/platform/provisioning': typeof AuthenticatedPlatformProvisioningRouteRouteWithChildren
  '/_authenticated/platform/$': typeof AuthenticatedPlatformSplatRoute
  '/_authenticated/platform/dashboard': typeof AuthenticatedPlatformDashboardRoute
  '/_authenticated/platform/': typeof AuthenticatedPlatformIndexRoute
  '/_authenticated/platform/companies/$companyId': typeof AuthenticatedPlatformCompaniesCompanyIdRoute
  '/_authenticated/platform/provisioning/$jobId': typeof AuthenticatedPlatformProvisioningJobIdRoute
  '/_authenticated/platform/provisioning/failed': typeof AuthenticatedPlatformProvisioningFailedRoute
  '/_authenticated/platform/provisioning/health': typeof AuthenticatedPlatformProvisioningHealthRoute
  '/_authenticated/platform/provisioning/history': typeof AuthenticatedPlatformProvisioningHistoryRoute
  '/_authenticated/platform/provisioning/queue': typeof AuthenticatedPlatformProvisioningQueueRoute
  '/_authenticated/platform/tenants/$tenantId': typeof AuthenticatedPlatformTenantsTenantIdRoute
  '/_authenticated/platform/companies/': typeof AuthenticatedPlatformCompaniesIndexRoute
  '/_authenticated/platform/provisioning/': typeof AuthenticatedPlatformProvisioningIndexRoute
  '/_authenticated/platform/tenants/': typeof AuthenticatedPlatformTenantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/403'
    | '/500'
    | '/auth'
    | '/docs'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/auth/callback'
    | '/docs/$'
    | '/docs/'
    | '/platform/provisioning'
    | '/platform/$'
    | '/platform/dashboard'
    | '/platform/'
    | '/platform/companies/$companyId'
    | '/platform/provisioning/$jobId'
    | '/platform/provisioning/failed'
    | '/platform/provisioning/health'
    | '/platform/provisioning/history'
    | '/platform/provisioning/queue'
    | '/platform/tenants/$tenantId'
    | '/platform/companies/'
    | '/platform/provisioning/'
    | '/platform/tenants/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | '/500'
    | '/auth'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/auth/callback'
    | '/docs/$'
    | '/docs'
    | '/platform/$'
    | '/platform/dashboard'
    | '/platform'
    | '/platform/companies/$companyId'
    | '/platform/provisioning/$jobId'
    | '/platform/provisioning/failed'
    | '/platform/provisioning/health'
    | '/platform/provisioning/history'
    | '/platform/provisioning/queue'
    | '/platform/tenants/$tenantId'
    | '/platform/companies'
    | '/platform/provisioning'
    | '/platform/tenants'
  id:
    | '__root__'
    | '/'
    | '/403'
    | '/500'
    | '/_authenticated'
    | '/auth'
    | '/docs'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/auth/callback'
    | '/docs/$'
    | '/docs/'
    | '/_authenticated/platform/provisioning'
    | '/_authenticated/platform/$'
    | '/_authenticated/platform/dashboard'
    | '/_authenticated/platform/'
    | '/_authenticated/platform/companies/$companyId'
    | '/_authenticated/platform/provisioning/$jobId'
    | '/_authenticated/platform/provisioning/failed'
    | '/_authenticated/platform/provisioning/health'
    | '/_authenticated/platform/provisioning/history'
    | '/_authenticated/platform/provisioning/queue'
    | '/_authenticated/platform/tenants/$tenantId'
    | '/_authenticated/platform/companies/'
    | '/_authenticated/platform/provisioning/'
    | '/_authenticated/platform/tenants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R403Route: typeof R403Route
  R500Route: typeof R500Route
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/500': {
      id: '/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof R500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof DocsRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/platform/': {
      id: '/_authenticated/platform/'
      path: '/platform'
      fullPath: '/platform/'
      preLoaderRoute: typeof AuthenticatedPlatformIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/platform/dashboard': {
      id: '/_authenticated/platform/dashboard'
      path: '/platform/dashboard'
      fullPath: '/platform/dashboard'
      preLoaderRoute: typeof AuthenticatedPlatformDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/platform/$': {
      id: '/_authenticated/platform/$'
      path: '/platform/$'
      fullPath: '/platform/$'
      preLoaderRoute: typeof AuthenticatedPlatformSplatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/platform/provisioning': {
      id: '/_authenticated/platform/provisioning'
      path: '/platform/provisioning'
      fullPath: '/platform/provisioning'
      preLoaderRoute: typeof AuthenticatedPlatformProvisioningRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/platform/tenants/': {
      id: '/_authenticated/platform/tenants/'
      path: '/platform/tenants'
      fullPath: '/platform/tenants/'
      preLoaderRoute: typeof AuthenticatedPlatformTenantsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/platform/provisioning/': {
      id: '/_authenticated/platform/provisioning/'
      path: '/'
      fullPath: '/platform/provisioning/'
      preLoaderRoute: typeof AuthenticatedPlatformProvisioningIndexRouteImport
      parentRoute: typeof AuthenticatedPlatformProvisioningRouteRoute
    }
    '/_authenticated/platform/companies/': {
      id: '/_authenticated/platform/companies/'
      path: '/platform/companies'
      fullPath: '/platform/companies/'
      preLoaderRoute: typeof AuthenticatedPlatformCompaniesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/platform/tenants/$tenantId': {
      id: '/_authenticated/platform/tenants/$tenantId'
      path: '/platform/tenants/$tenantId'
      fullPath: '/platform/tenants/$tenantId'
      preLoaderRoute: typeof AuthenticatedPlatformTenantsTenantIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/platform/provisioning/queue': {
      id: '/_authenticated/platform/provisioning/queue'
      path: '/queue'
      fullPath: '/platform/provisioning/queue'
      preLoaderRoute: typeof AuthenticatedPlatformProvisioningQueueRouteImport
      parentRoute: typeof AuthenticatedPlatformProvisioningRouteRoute
    }
    '/_authenticated/platform/provisioning/history': {
      id: '/_authenticated/platform/provisioning/history'
      path: '/history'
      fullPath: '/platform/provisioning/history'
      preLoaderRoute: typeof AuthenticatedPlatformProvisioningHistoryRouteImport
      parentRoute: typeof AuthenticatedPlatformProvisioningRouteRoute
    }
    '/_authenticated/platform/provisioning/health': {
      id: '/_authenticated/platform/provisioning/health'
      path: '/health'
      fullPath: '/platform/provisioning/health'
      preLoaderRoute: typeof AuthenticatedPlatformProvisioningHealthRouteImport
      parentRoute: typeof AuthenticatedPlatformProvisioningRouteRoute
    }
    '/_authenticated/platform/provisioning/failed': {
      id: '/_authenticated/platform/provisioning/failed'
      path: '/failed'
      fullPath: '/platform/provisioning/failed'
      preLoaderRoute: typeof AuthenticatedPlatformProvisioningFailedRouteImport
      parentRoute: typeof AuthenticatedPlatformProvisioningRouteRoute
    }
    '/_authenticated/platform/provisioning/$jobId': {
      id: '/_authenticated/platform/provisioning/$jobId'
      path: '/$jobId'
      fullPath: '/platform/provisioning/$jobId'
      preLoaderRoute: typeof AuthenticatedPlatformProvisioningJobIdRouteImport
      parentRoute: typeof AuthenticatedPlatformProvisioningRouteRoute
    }
    '/_authenticated/platform/companies/$companyId': {
      id: '/_authenticated/platform/companies/$companyId'
      path: '/platform/companies/$companyId'
      fullPath: '/platform/companies/$companyId'
      preLoaderRoute: typeof AuthenticatedPlatformCompaniesCompanyIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedPlatformProvisioningRouteRouteChildren {
  AuthenticatedPlatformProvisioningJobIdRoute: typeof AuthenticatedPlatformProvisioningJobIdRoute
  AuthenticatedPlatformProvisioningFailedRoute: typeof AuthenticatedPlatformProvisioningFailedRoute
  AuthenticatedPlatformProvisioningHealthRoute: typeof AuthenticatedPlatformProvisioningHealthRoute
  AuthenticatedPlatformProvisioningHistoryRoute: typeof AuthenticatedPlatformProvisioningHistoryRoute
  AuthenticatedPlatformProvisioningQueueRoute: typeof AuthenticatedPlatformProvisioningQueueRoute
  AuthenticatedPlatformProvisioningIndexRoute: typeof AuthenticatedPlatformProvisioningIndexRoute
}

const AuthenticatedPlatformProvisioningRouteRouteChildren: AuthenticatedPlatformProvisioningRouteRouteChildren =
  {
    AuthenticatedPlatformProvisioningJobIdRoute:
      AuthenticatedPlatformProvisioningJobIdRoute,
    AuthenticatedPlatformProvisioningFailedRoute:
      AuthenticatedPlatformProvisioningFailedRoute,
    AuthenticatedPlatformProvisioningHealthRoute:
      AuthenticatedPlatformProvisioningHealthRoute,
    AuthenticatedPlatformProvisioningHistoryRoute:
      AuthenticatedPlatformProvisioningHistoryRoute,
    AuthenticatedPlatformProvisioningQueueRoute:
      AuthenticatedPlatformProvisioningQueueRoute,
    AuthenticatedPlatformProvisioningIndexRoute:
      AuthenticatedPlatformProvisioningIndexRoute,
  }

const AuthenticatedPlatformProvisioningRouteRouteWithChildren =
  AuthenticatedPlatformProvisioningRouteRoute._addFileChildren(
    AuthenticatedPlatformProvisioningRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedPlatformProvisioningRouteRoute: typeof AuthenticatedPlatformProvisioningRouteRouteWithChildren
  AuthenticatedPlatformSplatRoute: typeof AuthenticatedPlatformSplatRoute
  AuthenticatedPlatformDashboardRoute: typeof AuthenticatedPlatformDashboardRoute
  AuthenticatedPlatformIndexRoute: typeof AuthenticatedPlatformIndexRoute
  AuthenticatedPlatformCompaniesCompanyIdRoute: typeof AuthenticatedPlatformCompaniesCompanyIdRoute
  AuthenticatedPlatformTenantsTenantIdRoute: typeof AuthenticatedPlatformTenantsTenantIdRoute
  AuthenticatedPlatformCompaniesIndexRoute: typeof AuthenticatedPlatformCompaniesIndexRoute
  AuthenticatedPlatformTenantsIndexRoute: typeof AuthenticatedPlatformTenantsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedPlatformProvisioningRouteRoute:
    AuthenticatedPlatformProvisioningRouteRouteWithChildren,
  AuthenticatedPlatformSplatRoute: AuthenticatedPlatformSplatRoute,
  AuthenticatedPlatformDashboardRoute: AuthenticatedPlatformDashboardRoute,
  AuthenticatedPlatformIndexRoute: AuthenticatedPlatformIndexRoute,
  AuthenticatedPlatformCompaniesCompanyIdRoute:
    AuthenticatedPlatformCompaniesCompanyIdRoute,
  AuthenticatedPlatformTenantsTenantIdRoute:
    AuthenticatedPlatformTenantsTenantIdRoute,
  AuthenticatedPlatformCompaniesIndexRoute:
    AuthenticatedPlatformCompaniesIndexRoute,
  AuthenticatedPlatformTenantsIndexRoute:
    AuthenticatedPlatformTenantsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DocsRouteChildren {
  DocsSplatRoute: typeof DocsSplatRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSplatRoute: DocsSplatRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R403Route: R403Route,
  R500Route: R500Route,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
