-- TOMBSTONED — Gate 3.8 demo-credential history repair (2026-07-28).
--
-- This migration previously seeded two demo accounts (admin@demo.test,
-- member@demo.test) directly into auth.users / auth.identities with a
-- hard-coded password literal, plus matching public.user_roles rows.
--
-- Removed because:
--   * it shipped a known credential into every environment, including
--     production and fresh replays;
--   * it violated the Gate 3.8 clean-replay residue contract (auth.users
--     MUST contain 0 rows after a complete replay).
--
-- It defined no schema objects, so tombstoning is behaviour-preserving for
-- schema. Existing environments retain any rows already created; those are
-- removed operationally, not by migration.
--
-- Intentionally no executable statements below this line.
