// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fplgjhbngvzfpepstvry.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwbGdqaGJuZ3Z6ZnBlcHN0dnJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM4Mjc0MDMsImV4cCI6MjA5OTQwMzQwM30.XGU3E0UcoA0MYtxOhxYr9RDM4Ivo7WWq7UtFhhzC6tI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});